name: 'Deploy to aws s3'
description: 'Deploy a static website to AWS s3.'
inputs:
  bucket:
    description: 'The s3 bucket name.'
    required: true
  bucket-region:
    description: 'The location of the bucket'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'The folder of deployable files'
    required: true
outputs:
  website-url:
    description: 'Output the website url'
runs:
  using: node20
  main: 'main.js'
